version: '3.7'
services:
  site-inventory-app:
    build:
      context: .
    container_name: site-inventory-app
    depends_on:
      - site-inventory-db
    networks:
      site-inventory-net:
        aliases:
          - site-inventory-app
    ports:
      - 8087:8087
  site-inventory-db:
    image: postgres:12-alpine
    container_name: site-inventory-db
    environment:
      POSTGRES_USER: siteinventory
      POSTGRES_PASSWORD: siteinventory
    networks:
      site-inventory-net:
        aliases:
          - site-inventory-db
networks:
  site-inventory-net:

