version: '3.7'
services:
  iwf-repository-app:
    build:
      context: .
    depends_on:
      - iwf-repository-db
    networks:
      iwf-repository-net:
        aliases:
          - iwf-repository-app
    ports:
      - 8087:8087
  iwf-repository-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: iwf-repository
      POSTGRES_PASSWORD: iwf-repository
    networks:
      iwf-repository-net:
        aliases:
          - iwf-repository-db
networks:
  iwf-repository-net:
