version: '3.7'
services:
  iwf-repository-app:
    build:
      context: .
    depends_on:
      - iwf-repository-db
    networks:
      iwf-repository-net:
        aliases:
          - iwf-repository-app
    ports:
      - 8087:8087
    command: java -Dspring.profiles.active=dev -Dspring.datasource.url=jdbc:postgresql://iwf-repository-db:5432/iwf-repository -jar app.jar
  iwf-repository-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: iwf-repository
      POSTGRES_PASSWORD: iwf-repository
    networks:
      iwf-repository-net:
        aliases:
          - iwf-repository-db
networks:
  iwf-repository-net:
